/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import Mathlib.RingTheory.MvPowerSeries.Equiv
public import Mathlib.Algebra.Module.SpanRankOperations
public import Mathlib.RingTheory.Ideal.Quotient.Noetherian
public import Mathlib.RingTheory.Regular.RegularSequence
public import FLT.Mathlib.RingTheory.Flat.TorsionFree

/-!
# Böckle presentations of deformation rings

This file packages the commutative-algebra data used in the Böckle step of the
hardly ramified lifting theorem.  A balanced presentation has the form

`R⟦X₁, ..., Xᵣ⟧ / (f₁, ..., fₛ)` with `s ≤ r`.

Once the relation sequence followed by a uniformizer is weakly regular, the
uniformizer acts regularly on the quotient.  Over a DVR this implies flatness.
-/

@[expose] public section

namespace Deformation

open RingTheory

universe u

/-- An ideal can be generated by at most `n` elements.  The list formulation records the
actual relations needed by a power-series presentation, including their cardinality bound. -/
def Ideal.IsGeneratedByAtMost {A : Type*} [CommRing A] (I : Ideal A) (n : ℕ) : Prop :=
  ∃ relations : List A, relations.length ≤ n ∧ Ideal.ofList relations = I

/-- A bound on the minimum number of module generators of a finitely generated ideal produces
an actual list of ideal generators satisfying the same bound.  This is the commutative-algebra
bridge from an obstruction-space dimension estimate to the relation list in a Böckle
presentation. -/
theorem Ideal.IsGeneratedByAtMost.of_spanFinrank_le
    {A : Type*} [CommRing A] (I : Ideal A) (hI : Submodule.FG I) {n : ℕ}
    (h : I.spanFinrank ≤ n) : Ideal.IsGeneratedByAtMost I n := by
  classical
  obtain ⟨relations, hcard, hspan⟩ :=
    Submodule.FG.exists_span_finset_card_eq_spanFinrank hI
  refine ⟨relations.toList, ?_, ?_⟩
  · simpa [hcard] using h
  · simpa [Ideal.ofList, Ideal.submodule_span_eq] using hspan

/-- A balanced power-series presentation of an `R`-algebra.  The inequality between the
number of relations and variables is the output of Böckle's obstruction-theory argument. -/
structure BocklePresentation
    (R D : Type u) [CommRing R] [CommRing D] [Algebra R D] where
  /-- The number of power-series variables. -/
  numVariables : ℕ
  /-- The relations defining the quotient. -/
  relations : List (MvPowerSeries (Fin numVariables) R)
  /-- There are no more relations than variables. -/
  relations_le_variables : relations.length ≤ numVariables
  /-- The presented quotient is the deformation ring. -/
  quotientEquiv : Nonempty
    ((MvPowerSeries (Fin numVariables) R ⧸ Ideal.ofList relations) ≃ₐ[R] D)

/-- Concrete data from which a Böckle presentation is assembled.  This separates the
deformation-theoretic work into three independently checkable assertions: constructing a
surjection from a finite-variable power-series ring, listing generators of its kernel, and
proving that the list has no more entries than variables. -/
structure BocklePresentationInput
    (R D : Type u) [CommRing R] [CommRing D] [Algebra R D] where
  /-- The number of tangent parameters. -/
  numVariables : ℕ
  /-- The power-series map furnished by the universal deformation. -/
  map : MvPowerSeries (Fin numVariables) R →ₐ[R] D
  /-- The chosen parameters topologically generate the deformation ring. -/
  map_surjective : Function.Surjective map
  /-- A finite obstruction list cutting out the deformation ring. -/
  relations : List (MvPowerSeries (Fin numVariables) R)
  /-- Böckle's numerical inequality between obstructions and tangent parameters. -/
  relations_le_variables : relations.length ≤ numVariables
  /-- The obstruction list generates exactly the kernel of the power-series map. -/
  relationIdeal_eq_ker : Ideal.ofList relations = RingHom.ker map.toRingHom

/-- The first isomorphism theorem turns explicit balanced power-series quotient data into a
`BocklePresentation`. -/
noncomputable def BocklePresentationInput.toBocklePresentation
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (P : BocklePresentationInput R D) : BocklePresentation R D where
  numVariables := P.numVariables
  relations := P.relations
  relations_le_variables := P.relations_le_variables
  quotientEquiv := ⟨
    (Ideal.quotientEquivAlgOfEq R P.relationIdeal_eq_ker).trans
      (Ideal.quotientKerAlgEquivOfSurjective P.map_surjective)⟩

/-- A surjective power-series map whose kernel has at most as many generators as variables
supplies all the concrete input to a balanced Böckle presentation. -/
theorem exists_bocklePresentationInput_of_surjective_of_kernel_generatedByAtMost
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (numVariables : ℕ)
    (f : MvPowerSeries (Fin numVariables) R →ₐ[R] D)
    (hf : Function.Surjective f)
    (hker : Ideal.IsGeneratedByAtMost (RingHom.ker f.toRingHom) numVariables) :
    Nonempty (BocklePresentationInput R D) := by
  obtain ⟨relations, hrelations, hker⟩ := hker
  exact ⟨{
    numVariables := numVariables
    map := f
    map_surjective := hf
    relations := relations
    relations_le_variables := hrelations
    relationIdeal_eq_ker := hker }⟩

/-- The abstract commutative-algebra endpoint of Böckle's tangent--obstruction argument.
It remains only to construct the power-series surjection and bound the number of generators
of its kernel. -/
theorem exists_bocklePresentation_of_surjective_of_kernel_generatedByAtMost
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (numVariables : ℕ)
    (f : MvPowerSeries (Fin numVariables) R →ₐ[R] D)
    (hf : Function.Surjective f)
    (hker : Ideal.IsGeneratedByAtMost (RingHom.ker f.toRingHom) numVariables) :
    Nonempty (BocklePresentation R D) := by
  obtain ⟨P⟩ := exists_bocklePresentationInput_of_surjective_of_kernel_generatedByAtMost
    numVariables f hf hker
  exact ⟨P.toBocklePresentation⟩

/-- Böckle's presentation follows directly from a surjective power-series map once obstruction
theory bounds the minimum number of generators of its kernel by the number of tangent
parameters.  No choice of relations is needed in the statement: Noetherianity extracts a
minimal finite generating list. -/
theorem exists_bocklePresentation_of_surjective_of_kernel_spanFinrank_le
    {R D : Type u} [CommRing R] [IsNoetherianRing R] [CommRing D] [Algebra R D]
    (numVariables : ℕ)
    (f : MvPowerSeries (Fin numVariables) R →ₐ[R] D)
    (hf : Function.Surjective f)
    (hker : (RingHom.ker f.toRingHom).spanFinrank ≤ numVariables) :
    Nonempty (BocklePresentation R D) :=
  exists_bocklePresentation_of_surjective_of_kernel_generatedByAtMost numVariables f hf <|
    Ideal.IsGeneratedByAtMost.of_spanFinrank_le _
      (IsNoetherian.noetherian (RingHom.ker f.toRingHom)) hker

/-- A finite-variable Böckle presentation over a Noetherian coefficient ring makes the
presented deformation ring Noetherian. -/
noncomputable def BocklePresentation.isNoetherianRing
    {R D : Type u} [CommRing R] [IsNoetherianRing R] [CommRing D] [Algebra R D]
    (P : BocklePresentation R D) : IsNoetherianRing D := by
  let A := MvPowerSeries (Fin P.numVariables) R
  let e := Classical.choice P.quotientEquiv
  haveI : IsNoetherianRing A := inferInstance
  haveI : IsNoetherianRing (A ⧸ Ideal.ofList P.relations) := inferInstance
  exact isNoetherianRing_of_ringEquiv (A ⧸ Ideal.ofList P.relations) e.toRingEquiv

/-- The regular-sequence conclusion used at the end of Böckle's argument: the defining
relations followed by `π` form a weakly regular sequence in the power-series ring. -/
def BocklePresentation.IsRegularAt
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (P : BocklePresentation R D) (π : R) : Prop :=
  let A := MvPowerSeries (Fin P.numVariables) R
  RingTheory.Sequence.IsWeaklyRegular A
    (P.relations ++ [algebraMap R A π])

/-- The last term of a regular Böckle presentation acts regularly on the presented algebra. -/
theorem BocklePresentation.isSMulRegular_of_isRegularAt
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (P : BocklePresentation R D) {π : R} (hπ : P.IsRegularAt π) :
    IsSMulRegular D π := by
  let A := MvPowerSeries (Fin P.numVariables) R
  let e := Classical.choice P.quotientEquiv
  have htail :=
    (RingTheory.Sequence.isWeaklyRegular_append_iff A P.relations
      [algebraMap R A π]).mp hπ |>.2
  have hquotA : IsSMulRegular
      (A ⧸ (Ideal.ofList P.relations • (⊤ : Submodule A A)))
      (algebraMap R A π) :=
    (RingTheory.Sequence.isWeaklyRegular_singleton_iff _ _).mp htail
  have heq : (Ideal.ofList P.relations • (⊤ : Submodule A A)) =
      Ideal.ofList P.relations := by
    simpa using Ideal.smul_top_eq_map (M := A) (Ideal.ofList P.relations)
  let qlin : (A ⧸ (Ideal.ofList P.relations • (⊤ : Submodule A A))) ≃ₗ[R]
      (A ⧸ Ideal.ofList P.relations) :=
    (Submodule.quotEquivOfEq _ _ heq).restrictScalars R
  have hquotR : IsSMulRegular (A ⧸ Ideal.ofList P.relations) π := by
    rw [← qlin.isSMulRegular_congr π]
    intro x y hxy
    apply hquotA
    simpa [Algebra.smul_def] using hxy
  exact (e.toLinearEquiv.isSMulRegular_congr π).mp hquotR

/-- The precise output needed from finiteness plus Böckle's balanced-presentation argument. -/
structure BockleFinitenessData
    (R D : Type u) [CommRing R] [CommRing D] [Algebra R D] where
  /-- A balanced presentation of the deformation ring. -/
  presentation : BocklePresentation R D
  /-- A uniformizer of the coefficient DVR. -/
  uniformizer : R
  /-- The chosen uniformizer is irreducible. -/
  uniformizer_irreducible : Irreducible uniformizer
  /-- The deformation ring is finite over the coefficient ring. -/
  finite : Module.Finite R D
  /-- The defining relations followed by the uniformizer form a regular sequence. -/
  regularAt : presentation.IsRegularAt uniformizer

/-- The uniformizer supplied by Böckle finiteness data acts regularly on the deformation ring. -/
theorem BockleFinitenessData.uniformizer_isSMulRegular
    {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]
    (h : BockleFinitenessData R D) : IsSMulRegular D h.uniformizer :=
  h.presentation.isSMulRegular_of_isRegularAt h.regularAt

/-- Böckle finiteness data make the presented algebra flat over a coefficient DVR. -/
theorem BockleFinitenessData.flat
    {R D : Type u} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    [CommRing D] [Algebra R D] (h : BockleFinitenessData R D) :
    Module.Flat R D :=
  Module.Flat.of_isSMulRegular_irreducible
    h.uniformizer_irreducible h.uniformizer_isSMulRegular

end Deformation
