/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Deformations.Representable
public import FLT.Deformations.RepresentationTheory.Carayol
public import FLT.Deformations.RepresentationTheory.FiniteImage

/-!
# Carayol trace generation for universal deformations

This file assembles the linear algebra in `RepresentationTheory/Carayol` with universal
unframed deformation rings.  The closed trace algebra is kept explicit throughout: it is a
local residue algebra, the lifted representation is recovered over it, and universality then
forces it to be the whole deformation ring.
-/

@[expose] public section

open IsLocalRing

namespace Subalgebra

/-- A local coefficient subalgebra of a residue algebra has the same residue field as the
coefficient ring, provided its inclusion in the ambient residue algebra is local. -/
theorem isResidueAlgebra_of_isLocalHom_val
    {q A : Type*} [CommRing q] [CommRing A] [IsLocalRing q] [IsLocalRing A]
    [Algebra q A] [IsResidueAlgebra q A]
    (S : Subalgebra q A) [IsLocalRing S] [IsLocalHom S.val] :
    IsResidueAlgebra q S := by
  constructor
  intro y
  obtain ⟨s, rfl⟩ := IsLocalRing.residue_surjective (R := S) y
  obtain ⟨a, ha⟩ := IsResidueAlgebra.algebraMap_surjective q A
    (IsLocalRing.residue A (s : A))
  refine ⟨a, ?_⟩
  change IsLocalRing.residue S (algebraMap q S a) = IsLocalRing.residue S s
  letI : IsLocalHom S.val.toRingHom := isLocalHom_toRingHom S.val
  apply (IsLocalRing.ResidueField.map S.val.toRingHom).injective
  rw [IsLocalRing.ResidueField.map_residue, IsLocalRing.ResidueField.map_residue]
  exact ha

end Subalgebra

namespace FramedGaloisRep

universe u

variable {q A K n : Type u} [CommRing q] [IsLocalRing q]
  [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsLocalRing A]
  [Algebra q A] [IsLocalHom (algebraMap q A)] [IsResidueAlgebra q A]
  [IsProartinian A] [Field K] [NumberField K] [Fintype n] [DecidableEq n]

/-- The closure of the coefficient algebra generated by the traces of a framed
representation. -/
def closedTraceAlgebra (rho : FramedGaloisRep K A n) : Subalgebra q A :=
  (Algebra.adjoin q rho.traceSet).topologicalClosure

/-- The closed trace algebra is closed in the ambient coefficient ring. -/
theorem isClosed_closedTraceAlgebra (rho : FramedGaloisRep K A n) :
    IsClosed (rho.closedTraceAlgebra (q := q) : Set A) :=
  (Algebra.adjoin q rho.traceSet).isClosed_topologicalClosure

/-- Every trace of the representation belongs to its closed trace algebra. -/
theorem trace_mem_closedTraceAlgebra (rho : FramedGaloisRep K A n) (g) :
    Matrix.trace (rho.GL g : Matrix n n A) ∈ rho.closedTraceAlgebra (q := q) := by
  apply Subalgebra.le_topologicalClosure
  apply Algebra.subset_adjoin
  exact ⟨g, rfl⟩

/-- The closed trace algebra is local. -/
theorem closedTraceAlgebra_isLocalRing (rho : FramedGaloisRep K A n) :
    IsLocalRing (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isLocalRing_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- Its inclusion into the ambient coefficient ring is a local homomorphism. -/
theorem closedTraceAlgebra_isLocalHom_val (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))] :
    IsLocalHom (rho.closedTraceAlgebra (q := q)).val :=
  Subalgebra.isLocalHom_val_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- The closed trace algebra has the same residue field as the scalar ring. -/
theorem closedTraceAlgebra_isResidueAlgebra (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val] :
    IsResidueAlgebra q (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isResidueAlgebra_of_isLocalHom_val _

end FramedGaloisRep
