/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Deformations.Representable
public import FLT.Deformations.RepresentationTheory.Carayol
public import FLT.Deformations.RepresentationTheory.FiniteImage

/-!
# Carayol trace generation for universal deformations

This file assembles the linear algebra in `RepresentationTheory/Carayol` with universal
unframed deformation rings.  The closed trace algebra is kept explicit throughout: it is a
local residue algebra, the lifted representation is recovered over it, and universality then
forces it to be the whole deformation ring.
-/

@[expose] public section

open IsLocalRing

namespace Subalgebra

/-- A closed local coefficient subalgebra of a pro-Artinian residue algebra is
pro-Artinian when the common residue field is finite.

This is the standard closed-subalgebra theorem for pseudocompact rings.  Completeness is
inherited from closedness, while linearity of the topology is inherited from the ambient
ring.  For an open ideal `J` of the subalgebra, choose an ambient open ideal whose
intersection is contained in `J`.  The resulting intermediate quotient embeds in an
Artinian local ambient quotient; that quotient is finite because its residue field is
finite.  Hence the quotient by `J` is finite, and in particular Artinian.

The theorem belongs to the classical theory of pseudocompact rings (Gabriel, 1962, and
SGA 3, Exp. VII_B), so we place only this general topological-algebra fact behind the
project's pre-1990 boundary. -/
theorem isProartinian_of_isClosed_of_finite_residueField
    {q A : Type*} [CommRing q] [IsLocalRing q] [Finite (IsLocalRing.ResidueField q)]
    [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsLocalRing A]
    [Algebra q A] [IsResidueAlgebra q A] [IsProartinian A]
    (S : Subalgebra q A) (hS : IsClosed (S : Set A))
    [IsTopologicalRing S] [IsLocalRing S] [IsResidueAlgebra q S] : IsProartinian S := by
  knownin1980s

/-- A local coefficient subalgebra of a residue algebra has the same residue field as the
coefficient ring, provided its inclusion in the ambient residue algebra is local. -/
theorem isResidueAlgebra_of_isLocalHom_val
    {q A : Type*} [CommRing q] [CommRing A] [IsLocalRing q] [IsLocalRing A]
    [Algebra q A] [IsResidueAlgebra q A]
    (S : Subalgebra q A) [IsLocalRing S] [IsLocalHom S.val] :
    IsResidueAlgebra q S := by
  constructor
  intro y
  obtain ⟨s, rfl⟩ := IsLocalRing.residue_surjective (R := S) y
  obtain ⟨a, ha⟩ := IsResidueAlgebra.algebraMap_surjective q A
    (IsLocalRing.residue A (s : A))
  refine ⟨a, ?_⟩
  change IsLocalRing.residue S (algebraMap q S a) = IsLocalRing.residue S s
  letI : IsLocalHom S.val.toRingHom := isLocalHom_toRingHom S.val
  apply (IsLocalRing.ResidueField.map S.val.toRingHom).injective
  rw [IsLocalRing.ResidueField.map_residue, IsLocalRing.ResidueField.map_residue]
  exact ha

end Subalgebra

namespace FramedGaloisRep

universe u

variable {q A K n : Type u} [CommRing q] [IsLocalRing q]
  [Finite (IsLocalRing.ResidueField q)]
  [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsLocalRing A]
  [Algebra q A] [IsLocalHom (algebraMap q A)] [IsResidueAlgebra q A]
  [IsProartinian A] [Field K] [NumberField K] [Fintype n] [DecidableEq n]

/-- The closure of the coefficient algebra generated by the traces of a framed
representation. -/
def closedTraceAlgebra (rho : FramedGaloisRep K A n) : Subalgebra q A :=
  (Algebra.adjoin q rho.traceSet).topologicalClosure

/-- The closed trace algebra is closed in the ambient coefficient ring. -/
theorem isClosed_closedTraceAlgebra (rho : FramedGaloisRep K A n) :
    IsClosed (rho.closedTraceAlgebra (q := q) : Set A) :=
  (Algebra.adjoin q rho.traceSet).isClosed_topologicalClosure

/-- Every trace of the representation belongs to its closed trace algebra. -/
theorem trace_mem_closedTraceAlgebra (rho : FramedGaloisRep K A n) (g) :
    Matrix.trace (rho.GL g : Matrix n n A) ∈ rho.closedTraceAlgebra (q := q) := by
  apply Subalgebra.le_topologicalClosure
  apply Algebra.subset_adjoin
  exact ⟨g, rfl⟩

/-- The closed trace algebra is local. -/
theorem closedTraceAlgebra_isLocalRing (rho : FramedGaloisRep K A n) :
    IsLocalRing (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isLocalRing_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- Its inclusion into the ambient coefficient ring is a local homomorphism. -/
theorem closedTraceAlgebra_isLocalHom_val (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))] :
    IsLocalHom (rho.closedTraceAlgebra (q := q)).val :=
  Subalgebra.isLocalHom_val_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- The closed trace algebra has the same residue field as the scalar ring. -/
theorem closedTraceAlgebra_isResidueAlgebra (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val] :
    IsResidueAlgebra q (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isResidueAlgebra_of_isLocalHom_val _

/-- The closed trace algebra is pro-Artinian. -/
theorem closedTraceAlgebra_isProartinian (rho : FramedGaloisRep K A n)
    [IsTopologicalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val]
    [IsResidueAlgebra q (rho.closedTraceAlgebra (q := q))] :
    IsProartinian (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isProartinian_of_isClosed_of_finite_residueField _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- The scalar map into the closed trace algebra is local. -/
theorem closedTraceAlgebra_isLocalHom_algebraMap (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val] :
    IsLocalHom (algebraMap q (rho.closedTraceAlgebra (q := q))) := by
  letI : IsLocalHom (rho.closedTraceAlgebra (q := q)).val.toRingHom :=
    isLocalHom_toRingHom (rho.closedTraceAlgebra (q := q)).val
  let f := algebraMap q (rho.closedTraceAlgebra (q := q))
  let g := (rho.closedTraceAlgebra (q := q)).val.toRingHom
  haveI : IsLocalHom (g.comp f) := by
    rw [show g.comp f = algebraMap q A by ext; rfl]
    infer_instance
  exact isLocalHom_of_comp f g

/-- The closed trace algebra, with its induced topology, is an object of the deformation
category over the scalar ring. -/
theorem closedTraceAlgebra_isLocalProartinianAlgebra (rho : FramedGaloisRep K A n) :
    Deformation.IsLocalProartinianAlgebra q (rho.closedTraceAlgebra (q := q)) := by
  letI : IsTopologicalRing (rho.closedTraceAlgebra (q := q)) :=
    Subring.instIsTopologicalRing (rho.closedTraceAlgebra (q := q)).toSubring
  letI : IsLocalRing (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isLocalRing (q := q)
  letI : IsLocalHom (rho.closedTraceAlgebra (q := q)).val :=
    rho.closedTraceAlgebra_isLocalHom_val (q := q)
  letI : IsResidueAlgebra q (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isResidueAlgebra (q := q)
  letI : IsProartinian (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isProartinian (q := q)
  letI : IsLocalHom (algebraMap q (rho.closedTraceAlgebra (q := q))) :=
    rho.closedTraceAlgebra_isLocalHom_algebraMap (q := q)
  exact ⟨⟩

end FramedGaloisRep
