/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Deformations.Representable
public import FLT.Deformations.RepresentationTheory.Carayol
public import FLT.Deformations.RepresentationTheory.FiniteImage
public import Mathlib.FieldTheory.Galois.Profinite

/-!
# Carayol trace generation for universal deformations

This file assembles the linear algebra in `RepresentationTheory/Carayol` with universal
unframed deformation rings.  The closed trace algebra is kept explicit throughout: it is a
local residue algebra, the lifted representation is recovered over it, and universality then
forces it to be the whole deformation ring.
-/

@[expose] public section

open CategoryTheory IsLocalRing

namespace Subalgebra

/-- A closed local coefficient subalgebra of a pro-Artinian residue algebra is
pro-Artinian when the common residue field is finite.

This is the standard closed-subalgebra theorem for pseudocompact rings.  Completeness is
inherited from closedness, while linearity of the topology is inherited from the ambient
ring.  For an open ideal `J` of the subalgebra, choose an ambient open ideal whose
intersection is contained in `J`.  The resulting intermediate quotient embeds in an
Artinian local ambient quotient; that quotient is finite because its residue field is
finite.  Hence the quotient by `J` is finite, and in particular Artinian.

The theorem belongs to the classical theory of pseudocompact rings (Gabriel, 1962, and
SGA 3, Exp. VII_B), so we place only this general topological-algebra fact behind the
project's pre-1990 boundary. -/
theorem isProartinian_of_isClosed_of_finite_residueField
    {q A : Type*} [CommRing q] [IsLocalRing q] [Finite (IsLocalRing.ResidueField q)]
    [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsLocalRing A]
    [Algebra q A] [IsResidueAlgebra q A] [IsProartinian A]
    (S : Subalgebra q A) (hS : IsClosed (S : Set A))
    [IsTopologicalRing S] [IsLocalRing S] [IsResidueAlgebra q S] : IsProartinian S := by
  knownin1980s

/-- A local coefficient subalgebra of a residue algebra has the same residue field as the
coefficient ring, provided its inclusion in the ambient residue algebra is local. -/
theorem isResidueAlgebra_of_isLocalHom_val
    {q A : Type*} [CommRing q] [CommRing A] [IsLocalRing q] [IsLocalRing A]
    [Algebra q A] [IsResidueAlgebra q A]
    (S : Subalgebra q A) [IsLocalRing S] [IsLocalHom S.val] :
    IsResidueAlgebra q S := by
  constructor
  intro y
  obtain ⟨s, rfl⟩ := IsLocalRing.residue_surjective (R := S) y
  obtain ⟨a, ha⟩ := IsResidueAlgebra.algebraMap_surjective q A
    (IsLocalRing.residue A (s : A))
  refine ⟨a, ?_⟩
  change IsLocalRing.residue S (algebraMap q S a) = IsLocalRing.residue S s
  letI : IsLocalHom S.val.toRingHom := isLocalHom_toRingHom S.val
  apply (IsLocalRing.ResidueField.map S.val.toRingHom).injective
  rw [IsLocalRing.ResidueField.map_residue, IsLocalRing.ResidueField.map_residue]
  exact ha

end Subalgebra

namespace FramedGaloisRep

universe u un

variable {q A K : Type u} {n : Type un}
  [CommRing q] [IsLocalRing q]
  [Finite (IsLocalRing.ResidueField q)]
  [CommRing A] [TopologicalSpace A] [IsTopologicalRing A] [IsLocalRing A]
  [Algebra q A] [IsLocalHom (algebraMap q A)] [IsResidueAlgebra q A]
  [IsProartinian A] [Field K] [NumberField K] [Fintype n] [DecidableEq n]

/-- The closure of the coefficient algebra generated by the traces of a framed
representation. -/
def closedTraceAlgebra (rho : FramedGaloisRep K A n) : Subalgebra q A :=
  (Algebra.adjoin q rho.traceSet).topologicalClosure

/-- Saying that the closed trace algebra is the whole coefficient ring is exactly
topological trace generation. -/
theorem closedTraceAlgebra_eq_top_iff_isTopologicallyTraceGenerated
    (rho : FramedGaloisRep K A n) :
    rho.closedTraceAlgebra (q := q) = ⊤ ↔
      rho.IsTopologicallyTraceGenerated (k := q) := by
  constructor
  · intro h
    rw [IsTopologicallyTraceGenerated, dense_iff_closure_eq]
    have hcoe := congrArg
      (fun S : Subalgebra q A => (S : Set A)) h
    simpa only [closedTraceAlgebra, Subalgebra.topologicalClosure_coe,
      Algebra.coe_top] using hcoe
  · intro h
    rw [IsTopologicallyTraceGenerated] at h
    apply SetLike.coe_injective
    rw [closedTraceAlgebra, Subalgebra.topologicalClosure_coe]
    exact dense_iff_closure_eq.mp h

/-- The closed trace algebra is closed in the ambient coefficient ring. -/
theorem isClosed_closedTraceAlgebra (rho : FramedGaloisRep K A n) :
    IsClosed (rho.closedTraceAlgebra (q := q) : Set A) :=
  (Algebra.adjoin q rho.traceSet).isClosed_topologicalClosure

/-- Every trace of the representation belongs to its closed trace algebra. -/
theorem trace_mem_closedTraceAlgebra (rho : FramedGaloisRep K A n) (g) :
    Matrix.trace (rho.GL g : Matrix n n A) ∈ rho.closedTraceAlgebra (q := q) := by
  apply Subalgebra.le_topologicalClosure
  apply Algebra.subset_adjoin
  exact ⟨g, rfl⟩

/-- The closed trace algebra is local. -/
theorem closedTraceAlgebra_isLocalRing (rho : FramedGaloisRep K A n) :
    IsLocalRing (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isLocalRing_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- Its inclusion into the ambient coefficient ring is a local homomorphism. -/
theorem closedTraceAlgebra_isLocalHom_val (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))] :
    IsLocalHom (rho.closedTraceAlgebra (q := q)).val :=
  Subalgebra.isLocalHom_val_of_isClosed_of_isResidueAlgebra _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- The closed trace algebra has the same residue field as the scalar ring. -/
theorem closedTraceAlgebra_isResidueAlgebra (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val] :
    IsResidueAlgebra q (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isResidueAlgebra_of_isLocalHom_val _

/-- The closed trace algebra is pro-Artinian. -/
theorem closedTraceAlgebra_isProartinian (rho : FramedGaloisRep K A n)
    [IsTopologicalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val]
    [IsResidueAlgebra q (rho.closedTraceAlgebra (q := q))] :
    IsProartinian (rho.closedTraceAlgebra (q := q)) :=
  Subalgebra.isProartinian_of_isClosed_of_finite_residueField _
    (rho.isClosed_closedTraceAlgebra (q := q))

/-- The scalar map into the closed trace algebra is local. -/
theorem closedTraceAlgebra_isLocalHom_algebraMap (rho : FramedGaloisRep K A n)
    [IsLocalRing (rho.closedTraceAlgebra (q := q))]
    [IsLocalHom (rho.closedTraceAlgebra (q := q)).val] :
    IsLocalHom (algebraMap q (rho.closedTraceAlgebra (q := q))) := by
  letI : IsLocalHom (rho.closedTraceAlgebra (q := q)).val.toRingHom :=
    isLocalHom_toRingHom (rho.closedTraceAlgebra (q := q)).val
  let f := algebraMap q (rho.closedTraceAlgebra (q := q))
  let g := (rho.closedTraceAlgebra (q := q)).val.toRingHom
  haveI : IsLocalHom (g.comp f) := by
    rw [show g.comp f = algebraMap q A by ext; rfl]
    infer_instance
  exact isLocalHom_of_comp f g

/-- The closed trace algebra, with its induced topology, is an object of the deformation
category over the scalar ring. -/
theorem closedTraceAlgebra_isLocalProartinianAlgebra (rho : FramedGaloisRep K A n) :
    Deformation.IsLocalProartinianAlgebra q (rho.closedTraceAlgebra (q := q)) := by
  letI : IsTopologicalRing (rho.closedTraceAlgebra (q := q)) :=
    Subring.instIsTopologicalRing (rho.closedTraceAlgebra (q := q)).toSubring
  letI : IsLocalRing (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isLocalRing (q := q)
  letI : IsLocalHom (rho.closedTraceAlgebra (q := q)).val :=
    rho.closedTraceAlgebra_isLocalHom_val (q := q)
  letI : IsResidueAlgebra q (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isResidueAlgebra (q := q)
  letI : IsProartinian (rho.closedTraceAlgebra (q := q)) :=
    rho.closedTraceAlgebra_isProartinian (q := q)
  letI : IsLocalHom (algebraMap q (rho.closedTraceAlgebra (q := q))) :=
    rho.closedTraceAlgebra_isLocalHom_algebraMap (q := q)
  exact ⟨⟩

end FramedGaloisRep

namespace Deformation

universe u

set_option backward.isDefEq.respectTransparency false in
/-- Strict equivalence is literal equality over an object whose residue morphism is
injective: the permitted conjugating subgroup is then trivial. -/
theorem toRepnQuot_app_injective_of_toResidueField_injective
    {𝓞 : Type u} [CommRing 𝓞] [IsLocalRing 𝓞]
    {G : Type*} [Group G] [TopologicalSpace G]
    {n : Type} [Fintype n] [DecidableEq n]
    (R : ProartinianCat 𝓞)
    (hres : Function.Injective (ProartinianCat.toResidueField R).hom.toRingHom) :
    Function.Injective ((toRepnQuot n G 𝓞).app R) := by
  intro tau tau' h
  obtain ⟨g, hg⟩ := Quotient.exact h
  have hGLinj : Function.Injective
      (Matrix.GeneralLinearGroup.map (n := n)
        (ProartinianCat.toResidueField R).hom.toRingHom) := by
    apply Units.map_injective
    exact Matrix.map_injective hres
  have hgmap : Matrix.GeneralLinearGroup.map (n := n)
      (ProartinianCat.toResidueField R).hom.toRingHom g.1.ofConjAct = 1 := by
    have hgker : g.1.ofConjAct ∈
        (Matrix.GeneralLinearGroup.map (n := n)
          (ProartinianCat.toResidueField R).hom.toRingHom).ker := g.2
    exact MonoidHom.mem_ker.mp hgker
  have hgGL : g.1.ofConjAct = 1 := by
    apply hGLinj
    simpa only [map_one] using hgmap
  apply ContinuousMonoidHom.ext
  intro x
  have hx := DFunLike.congr_fun hg x
  change g.1.ofConjAct *
      DFunLike.coe (F := G →ₜ* GL n R) tau' x * g.1.ofConjAct⁻¹ =
    DFunLike.coe (F := G →ₜ* GL n R) tau x at hx
  rw [hgGL] at hx
  simpa only [one_mul, inv_one, mul_one] using hx.symm

set_option backward.isDefEq.respectTransparency false in
/-- Strictly conjugate representations define the same point of `repnQuotFunctor`. -/
theorem toRepnQuot_eq_of_strict_conjugate
    {𝓞 : Type u} [CommRing 𝓞] [IsLocalRing 𝓞]
    {G : Type*} [Group G] [TopologicalSpace G]
    {n : Type} [Fintype n] [DecidableEq n]
    (R : ProartinianCat 𝓞) (tau tau' : (repnFunctor n G 𝓞).obj R)
    (P : GL n R)
    (hP : Matrix.GeneralLinearGroup.map
      (ProartinianCat.toResidueField R).hom.toRingHom P = 1)
    (hconj : ∀ g, DFunLike.coe (F := G →ₜ* GL n R) tau g = P *
      DFunLike.coe (F := G →ₜ* GL n R) tau' g * P⁻¹) :
    (toRepnQuot n G 𝓞).app R tau = (toRepnQuot n G 𝓞).app R tau' := by
  apply Quotient.sound
  refine ⟨⟨ConjAct.toConjAct P, ?_⟩, ?_⟩
  · exact hP
  · apply ContinuousMonoidHom.ext
    intro g
    change P * DFunLike.coe (F := G →ₜ* GL n R) tau' g * P⁻¹ =
      DFunLike.coe (F := G →ₜ* GL n R) tau g
    exact (hconj g).symm

set_option backward.isDefEq.respectTransparency false in
/-- Representatives of the same strict-equivalence class have identical trace sets. -/
theorem traceSet_toFramedGaloisRep_eq_of_toRepnQuot_eq
    {𝓞 : Type u} [CommRing 𝓞] [IsLocalRing 𝓞]
    {K : Type*} [Field K] [NumberField K]
    {n : Type} [Fintype n] [DecidableEq n]
    (R : ProartinianCat 𝓞)
    (tau tau' : (repnFunctor n (Field.absoluteGaloisGroup K) 𝓞).obj R)
    (h : (toRepnQuot n (Field.absoluteGaloisGroup K) 𝓞).app R tau =
      (toRepnQuot n (Field.absoluteGaloisGroup K) 𝓞).app R tau') :
    (toFramedGaloisRep tau).traceSet = (toFramedGaloisRep tau').traceSet := by
  obtain ⟨P, hP⟩ := Quotient.exact h
  have htrace (g : Field.absoluteGaloisGroup K) :
      Matrix.trace (DFunLike.coe
        (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau g : Matrix n n R) =
        Matrix.trace (DFunLike.coe
          (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau' g : Matrix n n R) := by
    have hg := DFunLike.congr_fun hP g
    let P0 : GL n R := P.1.ofConjAct
    have hgmat :
        (P0 : Matrix n n R) *
            (DFunLike.coe
              (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau' g : Matrix n n R) *
            (↑P0⁻¹ : Matrix n n R) =
          (DFunLike.coe
            (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau g : Matrix n n R) := by
      exact congrArg Units.val hg
    calc
      Matrix.trace (DFunLike.coe
          (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau g : Matrix n n R) =
          Matrix.trace ((P0 : Matrix n n R) *
            (DFunLike.coe
              (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau' g : Matrix n n R) *
            (↑P0⁻¹ : Matrix n n R)) := congrArg Matrix.trace hgmat.symm
      _ = Matrix.trace (DFunLike.coe
          (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau' g : Matrix n n R) :=
        Matrix.trace_units_conj P0 (DFunLike.coe
          (F := Field.absoluteGaloisGroup K →ₜ* GL n R) tau' g : Matrix n n R)
  unfold FramedGaloisRep.traceSet
  rw [show (toFramedGaloisRep tau).GL = tau by
      exact FramedGaloisRep.GL.apply_symm_apply _,
    show (toFramedGaloisRep tau').GL = tau' by
      exact FramedGaloisRep.GL.apply_symm_apply _]
  exact congrArg Set.range (funext htrace)

/-- Topological trace generation depends only on the strict-equivalence class of a
representation. -/
theorem isTopologicallyTraceGenerated_toFramedGaloisRep_of_toRepnQuot_eq
    {𝓞 : Type u} [CommRing 𝓞] [IsLocalRing 𝓞]
    {K : Type*} [Field K] [NumberField K]
    {n : Type} [Fintype n] [DecidableEq n]
    (R : ProartinianCat 𝓞)
    (tau tau' : (repnFunctor n (Field.absoluteGaloisGroup K) 𝓞).obj R)
    (hgen : (toFramedGaloisRep tau).IsTopologicallyTraceGenerated (k := 𝓞))
    (h : (toRepnQuot n (Field.absoluteGaloisGroup K) 𝓞).app R tau =
      (toRepnQuot n (Field.absoluteGaloisGroup K) 𝓞).app R tau') :
    (toFramedGaloisRep tau').IsTopologicallyTraceGenerated (k := 𝓞) := by
  rw [FramedGaloisRep.IsTopologicallyTraceGenerated] at hgen ⊢
  rw [← traceSet_toFramedGaloisRep_eq_of_toRepnQuot_eq R tau tau' h]
  exact hgen

/-- Writing a representation supplied by `repnFunctor` as endomorphisms and then converting
back to matrices returns its original matrices. -/
theorem matrixMonoidHom_toRepresentation_apply
    {𝓞 : Type u} [CommRing 𝓞] [IsLocalRing 𝓞]
    {G : Type*} [Group G] [TopologicalSpace G]
    {n : Type} [Fintype n] [DecidableEq n]
    (tau : (repnFunctor n G 𝓞).obj .residueField) (g : G) :
    Slop.OddRep.matrixMonoidHom (toRepresentation tau) g =
      (DFunLike.coe (F := G →ₜ* GL n (ProartinianCat.residueField (𝓞 := 𝓞))) tau g :
        Matrix n n (ProartinianCat.residueField (𝓞 := 𝓞))) := by
  change LinearMap.toMatrixAlgEquiv'
      (Matrix.GeneralLinearGroup.toLin
        (DFunLike.coe
          (F := G →ₜ* GL n (ProartinianCat.residueField (𝓞 := 𝓞))) tau g) :
          (n → ProartinianCat.residueField (𝓞 := 𝓞)) →ₗ[
            ProartinianCat.residueField (𝓞 := 𝓞)]
          (n → ProartinianCat.residueField (𝓞 := 𝓞))) = _
  exact LinearMap.toMatrixAlgEquiv'_toLinAlgEquiv' _

noncomputable section UnrestrictedUniversal

local notation3 "Γ" K:max => Field.absoluteGaloisGroup K

variable (𝓞 : Type u) [CommRing 𝓞] [IsLocalRing 𝓞] [IsNoetherianRing 𝓞]
  [Finite (IsLocalRing.ResidueField 𝓞)]
  [IsAdicComplete (IsLocalRing.maximalIdeal 𝓞) 𝓞]
variable (K : Type u) [Field K] [NumberField K]
variable (n : Type) [Fintype n] [DecidableEq n]
variable (rho : (repnFunctor n (Γ K) 𝓞).obj .residueField)
variable [Representation.IsAbsolutelyIrreducible.{u} (toRepresentation rho)]

/-- The universal ring for unrestricted deformations of an absolutely irreducible residual
representation. -/
def unrestrictedUniversalRing : ProartinianCat 𝓞 :=
  (isCorepresentable_deformationFunctor n (Γ K) 𝓞 rho).has_corepresentation.choose

/-- The chosen corepresentation of the unrestricted deformation functor. -/
def unrestrictedUniversalRingCorepresentableBy :
    (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.CorepresentableBy
      (unrestrictedUniversalRing 𝓞 K n rho) :=
  (isCorepresentable_deformationFunctor n (Γ K) 𝓞 rho).has_corepresentation.choose_spec.some

/-- The universal unrestricted strict-equivalence class. -/
def unrestrictedUniversalElement :
    (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.obj
      (unrestrictedUniversalRing 𝓞 K n rho) :=
  (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv
    (CategoryTheory.CategoryStruct.id (unrestrictedUniversalRing 𝓞 K n rho))

/-- The classifying morphism of an unrestricted deformation class. -/
def unrestrictedClassifyingMap {A : ProartinianCat 𝓞}
    (x : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.obj A) :
    unrestrictedUniversalRing 𝓞 K n rho ⟶ A :=
  (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv.symm x

/-- Mapping the universal class along its classifying morphism recovers the prescribed
deformation class. -/
theorem unrestrictedUniversalElement_map_classifyingMap {A : ProartinianCat 𝓞}
    (x : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.obj A) :
    (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map
        (unrestrictedClassifyingMap 𝓞 K n rho x)
        (unrestrictedUniversalElement 𝓞 K n rho) = x := by
  unfold unrestrictedClassifyingMap unrestrictedUniversalElement
  rw [← (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv_eq]
  exact (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv.apply_symm_apply x

/-- Uniqueness of the classifying morphism. -/
theorem unrestrictedClassifyingMap_unique {A : ProartinianCat 𝓞}
    (x : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.obj A)
    (f : unrestrictedUniversalRing 𝓞 K n rho ⟶ A)
    (hf : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map f
      (unrestrictedUniversalElement 𝓞 K n rho) = x) :
    f = unrestrictedClassifyingMap 𝓞 K n rho x := by
  apply (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv.injective
  calc
    (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv f =
        (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map f
          (unrestrictedUniversalElement 𝓞 K n rho) := by
            rw [(unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv_eq]
            rfl
    _ = x := hf
    _ = (unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv
          (unrestrictedClassifyingMap 𝓞 K n rho x) :=
      ((unrestrictedUniversalRingCorepresentableBy 𝓞 K n rho).homEquiv.apply_symm_apply x).symm

/-- An endomorphism of the universal ring fixing the universal class is the identity. -/
theorem unrestrictedUniversalEndomorphism_eq_id
    (f : unrestrictedUniversalRing 𝓞 K n rho ⟶
      unrestrictedUniversalRing 𝓞 K n rho)
    (hf : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map f
      (unrestrictedUniversalElement 𝓞 K n rho) =
        unrestrictedUniversalElement 𝓞 K n rho) :
    f = CategoryTheory.CategoryStruct.id (unrestrictedUniversalRing 𝓞 K n rho) := by
  apply (unrestrictedClassifyingMap_unique 𝓞 K n rho
    (unrestrictedUniversalElement 𝓞 K n rho) f hf).trans
  symm
  apply unrestrictedClassifyingMap_unique
  exact CategoryTheory.ConcreteCategory.congr_hom
    ((deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map_id
      (unrestrictedUniversalRing 𝓞 K n rho))
    (unrestrictedUniversalElement 𝓞 K n rho)

/-- A chosen matrix-valued representative of the universal unrestricted deformation class. -/
def unrestrictedUniversalRepresentation :
    (repnFunctor n (Γ K) 𝓞).obj (unrestrictedUniversalRing 𝓞 K n rho) :=
  Quotient.out (unrestrictedUniversalElement 𝓞 K n rho).1

/-- The chosen universal unrestricted representative as a framed Galois representation. -/
def unrestrictedUniversalGaloisRep :
    FramedGaloisRep K (unrestrictedUniversalRing 𝓞 K n rho) n :=
  toFramedGaloisRep (unrestrictedUniversalRepresentation 𝓞 K n rho)

/-- The chosen representative maps to the universal strict-equivalence class. -/
theorem unrestrictedUniversalRepresentation_toRepnQuot :
    (toRepnQuot n (Γ K) 𝓞).app (unrestrictedUniversalRing 𝓞 K n rho)
      (unrestrictedUniversalRepresentation 𝓞 K n rho) =
        (unrestrictedUniversalElement 𝓞 K n rho).1 :=
  Quotient.out_eq' _

/-- Reduction of the chosen representative is strictly equivalent to the fixed residual
representation.  This is the residual condition carried by the universal quotient class. -/
theorem unrestrictedUniversalRepresentation_reduces_up_to_strictEquivalence :
    (toRepnQuot n (Γ K) 𝓞).app .residueField
      ((repnFunctor n (Γ K) 𝓞).map
        (ProartinianCat.toResidueField (unrestrictedUniversalRing 𝓞 K n rho))
        (unrestrictedUniversalRepresentation 𝓞 K n rho)) =
    (toRepnQuot n (Γ K) 𝓞).app .residueField rho := by
  have hmem := (unrestrictedUniversalElement 𝓞 K n rho).2
  change (repnQuotFunctor n (Γ K) 𝓞).map
      (ProartinianCat.isTerminalResidueField.from
        (unrestrictedUniversalRing 𝓞 K n rho))
      (unrestrictedUniversalElement 𝓞 K n rho).1 =
    (toRepnQuot n (Γ K) 𝓞).app .residueField rho at hmem
  rw [← unrestrictedUniversalRepresentation_toRepnQuot 𝓞 K n rho] at hmem
  calc
    _ = (repnQuotFunctor n (Γ K) 𝓞).map
        (ProartinianCat.toResidueField (unrestrictedUniversalRing 𝓞 K n rho))
        ((toRepnQuot n (Γ K) 𝓞).app (unrestrictedUniversalRing 𝓞 K n rho)
          (unrestrictedUniversalRepresentation 𝓞 K n rho)) :=
      (toRepnQuot n (Γ K) 𝓞).naturality_apply _ _
    _ = _ := by
      simpa only [Subsingleton.elim
        (ProartinianCat.isTerminalResidueField.from
          (unrestrictedUniversalRing 𝓞 K n rho))
        (ProartinianCat.toResidueField (unrestrictedUniversalRing 𝓞 K n rho))] using hmem

/-- Reduction of the chosen universal representative is exactly the fixed residual
representation. -/
theorem unrestrictedUniversalRepresentation_reduces :
    (repnFunctor n (Γ K) 𝓞).map
      (ProartinianCat.toResidueField (unrestrictedUniversalRing 𝓞 K n rho))
      (unrestrictedUniversalRepresentation 𝓞 K n rho) = rho := by
  apply toRepnQuot_app_injective_of_toResidueField_injective
  · exact RingHom.injective _
  · exact unrestrictedUniversalRepresentation_reduces_up_to_strictEquivalence 𝓞 K n rho

/-- Matrix form of exact residual compatibility, in the orientation used by the Carayol
trace-pairing argument. -/
theorem unrestrictedUniversalGaloisRep_matrix_reduces (g : Γ K) :
    Slop.OddRep.matrixMonoidHom (toRepresentation rho) g =
      ((unrestrictedUniversalGaloisRep 𝓞 K n rho).GL g :
        Matrix n n (unrestrictedUniversalRing 𝓞 K n rho)).map
        (ProartinianCat.toResidueField
          (unrestrictedUniversalRing 𝓞 K n rho)).hom.toRingHom := by
  have hred := congrArg (fun tau :
      (repnFunctor n (Γ K) 𝓞).obj .residueField ↦
        DFunLike.coe
          (F := Γ K →ₜ* GL n (ProartinianCat.residueField (𝓞 := 𝓞))) tau g)
    (unrestrictedUniversalRepresentation_reduces 𝓞 K n rho)
  calc
    Slop.OddRep.matrixMonoidHom (toRepresentation rho) g =
        (DFunLike.coe
          (F := Γ K →ₜ* GL n (ProartinianCat.residueField (𝓞 := 𝓞))) rho g :
            Matrix n n (ProartinianCat.residueField (𝓞 := 𝓞))) :=
      matrixMonoidHom_toRepresentation_apply rho g
    _ = ((DFunLike.coe
          (F := Γ K →ₜ* GL n (unrestrictedUniversalRing 𝓞 K n rho))
          (unrestrictedUniversalRepresentation 𝓞 K n rho) g :
            GL n (unrestrictedUniversalRing 𝓞 K n rho)) :
            Matrix n n (unrestrictedUniversalRing 𝓞 K n rho)).map
          (ProartinianCat.toResidueField
            (unrestrictedUniversalRing 𝓞 K n rho)).hom.toRingHom := by
      exact congrArg Units.val hred.symm
    _ = _ := by
      rw [show (unrestrictedUniversalGaloisRep 𝓞 K n rho).GL =
          unrestrictedUniversalRepresentation 𝓞 K n rho by
        exact FramedGaloisRep.GL.apply_symm_apply _]

/-- Burnside's theorem and the trace pairing produce an image basis over the universal ring
whose coordinates for every image matrix lie in the closed trace algebra. -/
theorem unrestrictedUniversalGaloisRep_exists_image_basis_recovering_coefficients :
    let D := unrestrictedUniversalRing 𝓞 K n rho
    let tau := unrestrictedUniversalGaloisRep 𝓞 K n rho
    let T := tau.closedTraceAlgebra (q := 𝓞)
    ∃ (g : n × n → Γ K) (b : Module.Basis (n × n) D (Matrix n n D)),
      (∀ ij, b ij = (tau.GL (g ij) : Matrix n n D)) ∧
      ∀ h ij, b.repr (tau.GL h : Matrix n n D) ij ∈ T := by
  let D := unrestrictedUniversalRing 𝓞 K n rho
  let tau := unrestrictedUniversalGaloisRep 𝓞 K n rho
  let T := tau.closedTraceAlgebra (q := 𝓞)
  letI : IsLocalRing T := tau.closedTraceAlgebra_isLocalRing (q := 𝓞)
  letI : IsLocalHom T.val := tau.closedTraceAlgebra_isLocalHom_val (q := 𝓞)
  let rhoM : Γ K →* Matrix n n D :=
    (Units.coeHom (Matrix n n D)).comp tau.GL.toMonoidHom
  apply Slop.OddRep.exists_image_basis_recovering_coefficients rhoM
    (toRepresentation rho)
    (f := (ProartinianCat.toResidueField D).hom.toRingHom) (S := T)
  · intro g
    rw [show rhoM g = (tau.GL g : Matrix n n D) by
      ext i j
      rfl]
    simpa only [D, tau] using
      unrestrictedUniversalGaloisRep_matrix_reduces 𝓞 K n rho g
  · intro g
    exact tau.trace_mem_closedTraceAlgebra (q := 𝓞) g

/-- The universal representation is strictly conjugate to a representation over its closed
trace algebra.  All nonclassical content needed for the matrix-order splitting was isolated
in `Matrix.exists_strict_conjugate_over_closed_local_subalgebra`; the basis and coordinates
supplied above discharge its concrete hypotheses. -/
theorem unrestrictedUniversalGaloisRep_exists_strict_conjugate_over_closedTraceAlgebra :
    let D := unrestrictedUniversalRing 𝓞 K n rho
    let tau := unrestrictedUniversalGaloisRep 𝓞 K n rho
    let T := tau.closedTraceAlgebra (q := 𝓞)
    ∃ (tauT : Γ K →ₜ* GL n T) (P : GL n D),
      Matrix.GeneralLinearGroup.map
        (ProartinianCat.toResidueField D).hom.toRingHom P = 1 ∧
      ∀ h, tau.GL h = P *
        Matrix.GeneralLinearGroup.map T.val.toRingHom (tauT h) * P⁻¹ := by
  let D := unrestrictedUniversalRing 𝓞 K n rho
  let tau := unrestrictedUniversalGaloisRep 𝓞 K n rho
  let T := tau.closedTraceAlgebra (q := 𝓞)
  letI : IsLocalRing T := tau.closedTraceAlgebra_isLocalRing (q := 𝓞)
  letI : IsLocalHom T.val := tau.closedTraceAlgebra_isLocalHom_val (q := 𝓞)
  obtain ⟨g, b, hb, hcoeff⟩ :=
    unrestrictedUniversalGaloisRep_exists_image_basis_recovering_coefficients
      𝓞 K n rho
  have hsurj : Function.Surjective
      ((ProartinianCat.toResidueField D).hom.toRingHom.comp T.val.toRingHom) := by
    intro y
    obtain ⟨a, rfl⟩ := IsLocalRing.residue_surjective (R := 𝓞) y
    refine ⟨algebraMap 𝓞 T a, ?_⟩
    change (ProartinianCat.toResidueField D).hom (algebraMap 𝓞 D a) =
      algebraMap 𝓞 (ProartinianCat.residueField (𝓞 := 𝓞)) a
    exact (ProartinianCat.toResidueField D).hom.commutes a
  exact Matrix.exists_strict_conjugate_over_closed_local_subalgebra
    (ProartinianCat.toResidueField D).hom.toRingHom T
    (tau.isClosed_closedTraceAlgebra (q := 𝓞)) hsurj tau.GL g b hb hcoeff

/-- The closed trace algebra of the unrestricted universal deformation is the entire
universal ring.  The descended representation gives a deformation over the closed algebra;
Yoneda rigidity then makes its inclusion split-surjective. -/
theorem unrestrictedUniversalGaloisRep_closedTraceAlgebra_eq_top :
    (unrestrictedUniversalGaloisRep 𝓞 K n rho).closedTraceAlgebra (q := 𝓞) = ⊤ := by
  let D := unrestrictedUniversalRing 𝓞 K n rho
  let tau := unrestrictedUniversalGaloisRep 𝓞 K n rho
  let T := tau.closedTraceAlgebra (q := 𝓞)
  letI : IsLocalProartinianAlgebra 𝓞 T :=
    tau.closedTraceAlgebra_isLocalProartinianAlgebra (q := 𝓞)
  let DT : ProartinianCat 𝓞 := ProartinianCat.of 𝓞 T
  let i : DT ⟶ D :=
    ⟨⟨T.val, continuous_subtype_val⟩⟩
  obtain ⟨tauT, P, hP, hconj⟩ :=
    unrestrictedUniversalGaloisRep_exists_strict_conjugate_over_closedTraceAlgebra
      𝓞 K n rho
  let tauTi : (repnFunctor n (Γ K) 𝓞).obj D :=
    (repnFunctor n (Γ K) 𝓞).map i tauT
  have hconj' : ∀ g, DFunLike.coe (F := Γ K →ₜ* GL n D) tau.GL g = P *
      DFunLike.coe (F := Γ K →ₜ* GL n D) tauTi g * P⁻¹ := by
    intro g
    simpa only [tauTi, repnFunctor_map, i] using hconj g
  have hstrict :
      (toRepnQuot n (Γ K) 𝓞).app D tau.GL =
        (toRepnQuot n (Γ K) 𝓞).app D tauTi :=
    toRepnQuot_eq_of_strict_conjugate D tau.GL tauTi P hP hconj'
  let xq : (repnQuotFunctor n (Γ K) 𝓞).obj DT :=
    (toRepnQuot n (Γ K) 𝓞).app DT tauT
  have hmapq : (repnQuotFunctor n (Γ K) 𝓞).map i xq =
      (unrestrictedUniversalElement 𝓞 K n rho).1 := by
    calc
      (repnQuotFunctor n (Γ K) 𝓞).map i xq =
          (toRepnQuot n (Γ K) 𝓞).app D tauTi := by
        exact ((toRepnQuot n (Γ K) 𝓞).naturality_apply i tauT).symm
      _ = (toRepnQuot n (Γ K) 𝓞).app D tau.GL := hstrict.symm
      _ = (unrestrictedUniversalElement 𝓞 K n rho).1 := by
        rw [show tau.GL = unrestrictedUniversalRepresentation 𝓞 K n rho by
          exact FramedGaloisRep.GL.apply_symm_apply _]
        exact unrestrictedUniversalRepresentation_toRepnQuot 𝓞 K n rho
  have hmemD := (unrestrictedUniversalElement 𝓞 K n rho).2
  change (repnQuotFunctor n (Γ K) 𝓞).map
      (ProartinianCat.isTerminalResidueField.from D)
      (unrestrictedUniversalElement 𝓞 K n rho).1 =
    (toRepnQuot n (Γ K) 𝓞).app .residueField rho at hmemD
  have hterminal :
      (ProartinianCat.isTerminalResidueField.from DT : DT ⟶
        ProartinianCat.residueField) =
      CategoryTheory.CategoryStruct.comp i
        (ProartinianCat.isTerminalResidueField.from D : D ⟶
          ProartinianCat.residueField) :=
    Subsingleton.elim _ _
  have hmemT : xq ∈ (deformationFunctor n (Γ K) 𝓞 rho).obj DT := by
    change (repnQuotFunctor n (Γ K) 𝓞).map
        (ProartinianCat.isTerminalResidueField.from DT) xq =
      (toRepnQuot n (Γ K) 𝓞).app .residueField rho
    rw [hterminal]
    calc
      (repnQuotFunctor n (Γ K) 𝓞).map
          (i ≫ ProartinianCat.isTerminalResidueField.from D) xq =
          (repnQuotFunctor n (Γ K) 𝓞).map
            (ProartinianCat.isTerminalResidueField.from D)
            ((repnQuotFunctor n (Γ K) 𝓞).map i xq) := by
        exact CategoryTheory.ConcreteCategory.congr_hom
          ((repnQuotFunctor n (Γ K) 𝓞).map_comp i
            (ProartinianCat.isTerminalResidueField.from D)) xq
      _ = _ := by rw [hmapq, hmemD]
  let x : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.obj DT := ⟨xq, hmemT⟩
  let c : D ⟶ DT := unrestrictedClassifyingMap 𝓞 K n rho x
  have hclass := unrestrictedUniversalElement_map_classifyingMap 𝓞 K n rho x
  have hfix : (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map (c ≫ i)
      (unrestrictedUniversalElement 𝓞 K n rho) =
        unrestrictedUniversalElement 𝓞 K n rho := by
    calc
      (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map (c ≫ i)
          (unrestrictedUniversalElement 𝓞 K n rho) =
          (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map i
            ((deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map c
              (unrestrictedUniversalElement 𝓞 K n rho)) := by
        exact CategoryTheory.ConcreteCategory.congr_hom
          ((deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map_comp c i)
          (unrestrictedUniversalElement 𝓞 K n rho)
      _ = (deformationFunctor n (Γ K) 𝓞 rho).toFunctor.map i x := by rw [hclass]
      _ = unrestrictedUniversalElement 𝓞 K n rho := by
        apply Subtype.ext
        exact hmapq
  have hci : c ≫ i = CategoryTheory.CategoryStruct.id D :=
    unrestrictedUniversalEndomorphism_eq_id 𝓞 K n rho (c ≫ i) hfix
  apply top_unique
  intro d _hd
  have happ := congrArg (fun f : D ⟶ D ↦ f.hom d) hci
  change i.hom (c.hom d) = d at happ
  change d ∈ T
  rw [← happ]
  exact (c.hom d).2

/-- The unrestricted universal deformation ring is topologically generated over its
coefficient ring by the traces of its chosen universal representation. -/
theorem unrestrictedUniversalGaloisRep_isTopologicallyTraceGenerated :
    (unrestrictedUniversalGaloisRep 𝓞 K n rho).IsTopologicallyTraceGenerated
      (k := 𝓞) :=
  (FramedGaloisRep.closedTraceAlgebra_eq_top_iff_isTopologicallyTraceGenerated
    (unrestrictedUniversalGaloisRep 𝓞 K n rho)).mp
      (unrestrictedUniversalGaloisRep_closedTraceAlgebra_eq_top 𝓞 K n rho)

end UnrestrictedUniversal

end Deformation
