/-
Copyright (c) 2026 The FLT Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The FLT Project
-/
module

public import FLT.Mathlib.RingTheory.LocalRing.Quotient
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Reduction of an algebra modulo a scalar

For an `R`-algebra `D` and `pi : R`, this file names the ideal `pi D`, the quotient `D / pi D`,
and the quotient of `R` which acts faithfully on it.  If `R` is a DVR with finite residue field
and `pi` is irreducible, that coefficient quotient is finite.
-/

@[expose] public section

namespace Deformation

universe u

variable {R D : Type u} [CommRing R] [CommRing D] [Algebra R D]

/-- The principal ideal `pi D` generated by a scalar in an `R`-algebra. -/
def scalarIdeal (pi : R) : Ideal D :=
  Ideal.span ({algebraMap R D pi} : Set D)

/-- The kernel ideal in `R` of its action on `D / pi D`. -/
def scalarCoefficientIdeal (pi : R) : Ideal R :=
  (scalarIdeal (D := D) pi).comap (algebraMap R D)

/-- The faithful coefficient quotient acting on `D / pi D`. -/
abbrev ModScalarCoefficient (pi : R) := R ⧸ scalarCoefficientIdeal (D := D) pi

/-- The algebra `D` reduced modulo the scalar `pi`. -/
abbrev ModScalarRing (pi : R) := D ⧸ scalarIdeal (D := D) pi

/-- The coefficient quotient acting on `D / pi D` is finite when `pi` is a uniformizer of a DVR
with finite residue field. -/
theorem finite_modScalarCoefficient
    [IsDomain R] [IsDiscreteValuationRing R] [IsNoetherianRing R]
    [Finite (IsLocalRing.ResidueField R)] (pi : R) (hpi : Irreducible pi) :
    Finite (ModScalarCoefficient (D := D) pi) := by
  apply (IsLocalRing.finite_quotient_iff (R := R)).mpr
  refine ⟨1, ?_⟩
  rw [pow_one, hpi.maximalIdeal_eq]
  apply Ideal.span_le.mpr
  rintro x (rfl : x = pi)
  change algebraMap R D pi ∈ scalarIdeal (D := D) pi
  exact Ideal.subset_span (Set.mem_singleton _)

end Deformation
