/-
Copyright (c) 2025 Kevin Buzzard. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kevin Buzzard
-/
module

public import FLT.Data.Hurwitz
public import FLT.Data.QHat
import Mathlib.CategoryTheory.Category.Init
import Mathlib.RingTheory.Flat.TorsionFree
import Mathlib.Tactic.Positivity.Finset

/-!
# Adelic Hurwitz quaternions

Base changes of the Hurwitz integers to `ℚ` and to `ZHat`, providing a
quaternion algebra over the rationals and its profinite completion as
free rank-4 modules over the corresponding base ring.

## Main definitions

* `HurwitzRat`: the rational quaternions `ℚ + ℚi + ℚj + ℚk`.
* `HurwitzHat`: the profinite Hurwitz quaternions, a free rank-4 module
  over `ZHat`.
-/

@[expose] public section

open scoped TensorProduct

/-- The base change of the Hurwitz quaternions to ZHat. -/
noncomputable def HurwitzHat : Type := 𝓞 ⊗[ℤ] ZHat

namespace HurwitzHat

/-- The base change of the Hurwitz quaternions to ZHat. -/
scoped notation "𝓞^" => HurwitzHat

noncomputable instance : Ring 𝓞^ := Algebra.TensorProduct.instRing

instance flat : Module.Flat ℤ 𝓞^ :=
  Module.Flat.instTensorProduct (R := ℤ) (S := ℤ) (M := 𝓞) (N := ZHat)

/-- The inclusion of the Hurwitz integers into their profinite completion. -/
noncomputable abbrev ofHurwitz : 𝓞 →ₐ[ℤ] 𝓞^ := Algebra.TensorProduct.includeLeft

lemma ofHurwitz_injective : Function.Injective ofHurwitz := by
  exact Algebra.TensorProduct.includeLeft_injective (R := ℤ) (S := ℤ) (A := 𝓞) (B := ZHat)
    Int.cast_injective

end HurwitzHat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
noncomputable def HurwitzRat : Type := ℚ ⊗[ℤ] 𝓞

namespace HurwitzRat

/-- The quaternion algebra ℚ + ℚi + ℚj + ℚk. -/
scoped notation "D" => HurwitzRat

noncomputable instance : Ring D := Algebra.TensorProduct.instRing

instance flat : Module.Flat ℤ D :=
  Module.Flat.instTensorProduct (R := ℤ) (S := ℤ) (M := ℚ) (N := 𝓞)

set_option backward.isDefEq.respectTransparency false in
/-- A nonzero Hurwitz integer becomes a unit after extending scalars to `ℚ`. -/
noncomputable def unitOfNeZero (a : 𝓞) (ha : a ≠ 0) : Dˣ where
  val := (1 : ℚ) ⊗ₜ a
  inv := ((Hurwitz.norm a : ℚ)⁻¹) ⊗ₜ star a
  val_inv := by
    rw [Algebra.TensorProduct.tmul_mul_tmul, one_mul, ← Hurwitz.norm_eq_mul_conj]
    rw [show (Hurwitz.norm a : 𝓞) = Hurwitz.norm a • (1 : 𝓞) by simp,
      TensorProduct.tmul_smul]
    change ((Hurwitz.norm a : ℤ) • (Hurwitz.norm a : ℚ)⁻¹) ⊗ₜ[ℤ] (1 : 𝓞) =
      ((1 : ℚ) ⊗ₜ[ℤ] (1 : 𝓞) : D)
    congr 1
    have hn : (Hurwitz.norm a : ℚ) ≠ 0 := by
      exact_mod_cast (Hurwitz.norm_eq_zero a).not.mpr ha
    simpa [zsmul_eq_mul] using mul_inv_cancel₀ hn
  inv_val := by
    rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one, Hurwitz.conj_mul_self]
    rw [show (Hurwitz.norm a : 𝓞) = Hurwitz.norm a • (1 : 𝓞) by simp,
      TensorProduct.tmul_smul]
    change ((Hurwitz.norm a : ℤ) • (Hurwitz.norm a : ℚ)⁻¹) ⊗ₜ[ℤ] (1 : 𝓞) =
      ((1 : ℚ) ⊗ₜ[ℤ] (1 : 𝓞) : D)
    congr 1
    have hn : (Hurwitz.norm a : ℚ) ≠ 0 := by
      exact_mod_cast (Hurwitz.norm_eq_zero a).not.mpr ha
    simpa [zsmul_eq_mul] using mul_inv_cancel₀ hn

set_option backward.isDefEq.respectTransparency false in
@[simp]
lemma coe_unitOfNeZero (a : 𝓞) (ha : a ≠ 0) :
    (unitOfNeZero a ha : D) = (1 : ℚ) ⊗ₜ a := rfl

end HurwitzRat

open scoped HurwitzRat HurwitzHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
noncomputable def HurwitzRatHat : Type := D ⊗[ℤ] ZHat

namespace HurwitzRatHat

/-- The "profinite Hurwitz quaternions" over the finite adeles of ℚ; a free rank 4 module
generated by 1, i, j, and (1+i+j+k)/2. -/
scoped notation "D^" => HurwitzRatHat

noncomputable instance : Ring D^ := Algebra.TensorProduct.instRing

/-- The inclusion from D=ℚ+ℚi+ℚj+ℚk to D ⊗ 𝔸, with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₁ : D →ₐ[ℤ] D^ := Algebra.TensorProduct.includeLeft
-- (Algebra.TensorProduct.assoc ℤ ℚ 𝓞 ZHat).symm.trans Algebra.TensorProduct.includeLeft

lemma injective_hRat :
    Function.Injective j₁ := by
  exact Algebra.TensorProduct.includeLeft_injective (R := ℤ) (S := ℤ) (A := D) (B := ZHat)
    Int.cast_injective

-- this stopped working in 4.29
noncomputable instance : Ring (ℚ ⊗[ℤ] 𝓞^) := Algebra.TensorProduct.instRing

-- this stopped working in 4.29
noncomputable instance : Ring (D ⊗[ℤ] ZHat) := Algebra.TensorProduct.instRing

-- in 4.29 I had to change all three ⊗ in the below to ⊗[ℤ]
/-- The inclusion from the profinite Hurwitz quaternions to to 𝔸+𝔸i+𝔸j+𝔸k,
with 𝔸 the finite adeles of ℚ. -/
noncomputable abbrev j₂ : 𝓞^ →ₐ[ℤ] D^ :=
  ((Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm : ℚ ⊗[ℤ] 𝓞^ ≃ₐ[ℤ] D ⊗[ℤ] ZHat).toAlgHom.comp
  (Algebra.TensorProduct.includeRight : 𝓞^ →ₐ[ℤ] ℚ ⊗[ℤ] 𝓞^)

lemma injective_zHat :
    Function.Injective j₂ := by
  exact (Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat).symm.injective.comp
    (Algebra.TensorProduct.includeRight_injective (R := ℤ) (A := ℚ) (B := 𝓞^)
      Int.cast_injective)

/-- The contraction to `𝓞` of the principal left ideal `𝓞^ y`. -/
noncomputable def contractedLeftIdeal (y : 𝓞^) : Submodule 𝓞 𝓞 where
  carrier := {a | ∃ b : 𝓞^, HurwitzHat.ofHurwitz a = b * y}
  zero_mem' := ⟨0, by simp⟩
  add_mem' := by
    rintro a b ⟨c, hc⟩ ⟨d, hd⟩
    refine ⟨c + d, ?_⟩
    rw [map_add, hc, hd, add_mul]
  smul_mem' := by
    rintro a b ⟨c, hc⟩
    refine ⟨HurwitzHat.ofHurwitz a * c, ?_⟩
    change HurwitzHat.ofHurwitz (a * b) = _
    rw [map_mul, hc, mul_assoc]

lemma mem_contractedLeftIdeal_iff {y : 𝓞^} {a : 𝓞} :
    a ∈ contractedLeftIdeal y ↔ ∃ b : 𝓞^, HurwitzHat.ofHurwitz a = b * y := Iff.rfl

set_option backward.isDefEq.respectTransparency false in
/-- A principal generator of the contraction of `𝓞^ y` also generates `y` after
extension to `𝓞^`, provided that a positive integer is a left multiple of `y`. -/
lemma exists_integral_generator {x y : 𝓞^} (N : ℕ+)
    (hN : HurwitzHat.ofHurwitz (N : 𝓞) = x * y) :
    ∃ a : 𝓞, a ≠ 0 ∧
      (∃ b : 𝓞^, HurwitzHat.ofHurwitz a = b * y) ∧
      (∃ c : 𝓞^, y = c * HurwitzHat.ofHurwitz a) := by
  let I := contractedLeftIdeal y
  have hNmem : (N : 𝓞) ∈ I := by
    exact ⟨x, hN⟩
  obtain ⟨a, haI⟩ := Hurwitz.left_ideal_princ I
  have ha : a ≠ 0 := by
    intro ha
    have hNzero : (N : 𝓞) = 0 := by
      rw [haI, ha] at hNmem
      rw [Submodule.mem_span_singleton] at hNmem
      obtain ⟨c, hc⟩ := hNmem
      simpa using hc.symm
    have hNne : (N : 𝓞) ≠ 0 := by exact_mod_cast N.ne_zero
    exact hNne hNzero
  have ha_mem : a ∈ I := by
    rw [haI, Submodule.mem_span_singleton]
    exact ⟨1, one_mul a⟩
  obtain ⟨b, hb⟩ := ha_mem
  have hnormpos : 0 < Hurwitz.norm a := lt_of_le_of_ne (Hurwitz.norm_nonneg a)
    (Ne.symm ((Hurwitz.norm_eq_zero a).not.mpr ha))
  have hnormnatpos : 0 < (Hurwitz.norm a).toNat :=
    Int.pos_iff_toNat_pos.mp hnormpos
  let A : ℕ+ := ⟨(Hurwitz.norm a).toNat, hnormnatpos⟩
  have hA : (A : ℤ) = Hurwitz.norm a := by
    exact Int.toNat_of_nonneg (Hurwitz.norm_nonneg a)
  let T := N * A
  obtain ⟨β, δ, hy⟩ := TensorProduct.exists_eq_tmul_one_add_pnat_smul T y
  change 𝓞^ at δ
  change y = HurwitzHat.ofHurwitz β + (T : ℤ) • δ at hy
  have hN' : (N : 𝓞^) = x * y := by
    simpa using hN
  have hN'' : ((N : ℤ) : 𝓞^) = x * y := by
    simpa using hN'
  have hTy : (T : ℤ) • (1 : 𝓞^) = ((A : ℤ) • x) * y := by
    rw [show (T : ℤ) = (N : ℤ) * (A : ℤ) by simp [T], mul_smul]
    simp only [zsmul_eq_mul]
    rw [mul_one]
    calc
      ((N : ℤ) : 𝓞^) * ((A : ℤ) : 𝓞^) =
          ((A : ℤ) : 𝓞^) * ((N : ℤ) : 𝓞^) := Int.cast_comm _ _
      _ = (((A : ℤ) : 𝓞^) * x) * y := by rw [hN'', mul_assoc]
  have hβ : β ∈ I := by
    refine ⟨1 - δ * ((A : ℤ) • x), ?_⟩
    calc
      HurwitzHat.ofHurwitz β = y - (T : ℤ) • δ := by rw [hy]; abel
      _ = y - δ * ((T : ℤ) • (1 : 𝓞^)) := by
        rw [zsmul_eq_mul, zsmul_eq_mul, mul_one, Int.cast_comm]
      _ = (1 - δ * ((A : ℤ) • x)) * y := by rw [hTy]; noncomm_ring
  rw [haI, Submodule.mem_span_singleton] at hβ
  obtain ⟨γ, hγ⟩ := hβ
  have hγ' : HurwitzHat.ofHurwitz β =
      HurwitzHat.ofHurwitz γ * HurwitzHat.ofHurwitz a := by
    rw [← hγ]
    change HurwitzHat.ofHurwitz (γ * a) = _
    rw [map_mul]
  refine ⟨a, ha, ⟨b, hb⟩, ?_⟩
  refine ⟨HurwitzHat.ofHurwitz γ + δ * ((N : ℤ) • HurwitzHat.ofHurwitz (star a)), ?_⟩
  rw [hy, hγ']
  rw [show (T : ℤ) = (N : ℤ) * (A : ℤ) by simp [T], hA, mul_smul]
  have hnorm : (Hurwitz.norm a : ℤ) • δ =
      (δ * HurwitzHat.ofHurwitz (star a)) * HurwitzHat.ofHurwitz a := by
    calc
      (Hurwitz.norm a : ℤ) • δ =
          δ * ((Hurwitz.norm a : ℤ) • (1 : 𝓞^)) := by
            rw [zsmul_eq_mul, zsmul_eq_mul, mul_one, Int.cast_comm]
      _ = δ * HurwitzHat.ofHurwitz (Hurwitz.norm a : 𝓞) := by simp
      _ = δ * HurwitzHat.ofHurwitz (star a * a) := by rw [Hurwitz.conj_mul_self]
      _ = (δ * HurwitzHat.ofHurwitz (star a)) * HurwitzHat.ofHurwitz a := by
        rw [map_mul, mul_assoc]
  rw [hnorm]
  simp only [zsmul_eq_mul]
  rw [add_mul]
  congr 1
  calc
    ((N : ℤ) : 𝓞^) *
        ((δ * HurwitzHat.ofHurwitz (star a)) * HurwitzHat.ofHurwitz a) =
        (((N : ℤ) : 𝓞^) * (δ * HurwitzHat.ofHurwitz (star a))) *
          HurwitzHat.ofHurwitz a := by noncomm_ring
    _ = ((((N : ℤ) : 𝓞^) * δ) * HurwitzHat.ofHurwitz (star a)) *
          HurwitzHat.ofHurwitz a := by noncomm_ring
    _ = ((δ * ((N : ℤ) : 𝓞^)) * HurwitzHat.ofHurwitz (star a)) *
          HurwitzHat.ofHurwitz a := by rw [Int.cast_comm]
    _ = (δ * (((N : ℤ) : 𝓞^) * HurwitzHat.ofHurwitz (star a))) *
          HurwitzHat.ofHurwitz a := by noncomm_ring

-- should I rearrange tensors? Not sure if D^ should be (ℚ ⊗ 𝓞) ⊗ ℤhat or ℚ ⊗ (𝓞 ⊗ Zhat)
set_option backward.isDefEq.respectTransparency false in
lemma canonicalForm (z : D^) : ∃ (N : ℕ+) (z' : 𝓞^), z = j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D) * j₂ z' := by
  let e := Algebra.TensorProduct.assoc ℤ ℤ ℤ ℚ 𝓞 ZHat
  obtain ⟨N, z', hz⟩ := TensorProduct.rat_canonicalForm (e z)
  refine ⟨N, z', ?_⟩
  apply e.injective
  rw [hz]
  have hj₂ : e (j₂ z') = (1 : ℚ) ⊗ₜ z' := by
    change e (e.symm (1 ⊗ₜ z')) = _
    simp
  have hj₁ : e (j₁ ((N⁻¹ : ℚ) ⊗ₜ 1 : D)) =
      (N⁻¹ : ℚ) ⊗ₜ ((1 : 𝓞) ⊗ₜ (1 : ZHat)) := by
    change e ((((N⁻¹ : ℚ) ⊗ₜ (1 : 𝓞)) : D) ⊗ₜ (1 : ZHat)) = _
    rw [Algebra.TensorProduct.assoc_tmul]
  rw [map_mul, hj₁, hj₂]
  rw [Algebra.TensorProduct.tmul_mul_tmul, mul_one]
  congr 1
  · simp
  · have hone : ((1 : 𝓞) ⊗ₜ[ℤ] (1 : ZHat)) = (1 : 𝓞 ⊗[ℤ] ZHat) :=
      (Algebra.TensorProduct.one_def (R := ℤ) (A := 𝓞) (B := ZHat)).symm
    rw [hone, one_mul]

lemma completed_units (z : D^ˣ) : ∃ (u : Dˣ) (v : 𝓞^ˣ), (z : D^) = j₁ u * j₂ v := sorry

end HurwitzRatHat
